FROM python:3.10-buster

WORKDIR /build

COPY bin /build/bin
COPY stignore_agent /build/stignore_agent
COPY setup.cfg pyproject.toml README.md LICENSE /build/

RUN pip3 install --upgrade setuptools wheel build
RUN pip3 install --upgrade -e '.'

ENTRYPOINT ["/usr/local/bin/stignore-agent"]
